# Generated by Django 3.2.12 on 2023-03-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-name']},
        ),
    ]
