# Generated by Django 3.2.12 on 2023-03-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['name', 'email'], name='Profile_pro_name_1813ee_idx'),
        ),
    ]
