# Generated by Django 4.2 on 2023-05-30 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='create_channel', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('channel_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='uploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(unique=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('age_restricted', models.BooleanField(default=False)),
                ('tags', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Comedy', 'Comedy'), ('Education', 'Education'), ('Sports', 'Sports'), ('Gaming', 'Gaming'), ('Music', 'Music'), ('News', 'News')], max_length=15)),
                ('channel_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_video_channel', to='studio.channel')),
            ],
        ),
    ]
