# Generated by Django 4.2 on 2023-05-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_channel_id_alter_uploadvideo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='channel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_video_channel', to='studio.channel'),
        ),
    ]
