# Generated by Django 4.2 on 2023-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_uploadvideo_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='handler',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
