# Generated by Django 4.2 on 2023-06-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_channel_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='thumbnail',
            field=models.TextField(),
        ),
    ]
