# Generated by Django 4.2 on 2023-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_alter_uploadvideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
