# Generated by Django 4.2 on 2023-06-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_uploadvideo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadvideo',
            name='user',
        ),
    ]
