# Generated by Django 4.2 on 2023-06-05 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_uploadvideo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='video_file',
            field=models.FileField(unique=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
