# Generated by Django 4.2 on 2023-06-08 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_alter_uploadvideo_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadvideo',
            name='video_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
