# Generated by Django 3.2.12 on 2023-03-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='doj',
            field=models.DateField(null=True, verbose_name='joining date'),
        ),
    ]
