# Generated by Django 3.2.12 on 2023-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_customuser_doj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email']},
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['firstname', 'email'], name='Profile_cus_firstna_8daf46_idx'),
        ),
    ]
