# Generated by Django 3.2.12 on 2023-04-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['lastname']},
        ),
    ]
