# Generated by Django 3.2.12 on 2023-04-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email']},
        ),
    ]
