# Generated by Django 3.2.12 on 2023-04-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_auto_20230405_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.IntegerField(default=1000),
        ),
    ]
