# Generated by Django 3.2.12 on 2023-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_customuser_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='doj',
            field=models.DateTimeField(null=True, verbose_name='joining Date'),
        ),
    ]
