# Generated by Django 3.2.12 on 2023-03-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_buyer',
            new_name='is_junior',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_saler',
            new_name='is_senior',
        ),
    ]
