# Generated by Django 3.2.12 on 2023-03-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230322_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='mark2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='result',
            name='mark3',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='result',
            name='mark4',
            field=models.IntegerField(default=4),
        ),
    ]
