# Generated by Django 3.2.12 on 2023-03-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_auto_20230321_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
