# Generated by Django 4.2 on 2023-05-15 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyUserToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verify_user_token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('otp', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
