# Generated by Django 3.2.12 on 2023-04-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endyear', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=20)),
                ('insights', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('region', models.CharField(max_length=20)),
                ('start_year', models.IntegerField()),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('country', models.CharField(max_length=50)),
                ('relavence', models.IntegerField()),
                ('postle', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('likelihood', models.IntegerField()),
            ],
        ),
    ]
