# Generated by Django 3.2.12 on 2023-04-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='endyear',
            new_name='end_year',
        ),
    ]
