# Generated by Django 3.2.12 on 2023-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230411_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='relavence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
