# Generated by Django 3.2.12 on 2023-04-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230411_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='added',
            field=models.DateTimeField(verbose_name='%B, %d %Y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='published',
            field=models.DateTimeField(max_length=50),
        ),
    ]
