# Generated by Django 3.2.12 on 2023-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230411_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
    ]
