# Generated by Django 3.2.12 on 2023-04-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dashboard_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='likelihood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
