# Generated by Django 4.1.7 on 2023-03-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=3)),
                ('empname', models.CharField(max_length=200)),
                ('empgender', models.CharField(max_length=10)),
                ('empemail', models.EmailField(max_length=254)),
                ('empdesignation', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
