# Generated by Django 3.2.12 on 2023-04-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userexample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetconfirmation',
            name='code',
            field=models.BigIntegerField(unique=True),
        ),
    ]
