# Generated by Django 3.2.12 on 2023-03-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='EmpDuration',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='EmpProfile2',
        ),
    ]
