# Generated by Django 3.2.12 on 2023-03-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20230313_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpProfile',
            field=models.FileField(upload_to='profile/'),
        ),
    ]
