# Generated by Django 3.2.12 on 2023-03-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_profile_pro_name_1813ee_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='Profile_pro_name_1813ee_idx',
        ),
    ]
