# Generated by Django 3.2.12 on 2023-03-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_alter_profile_csem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='c_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
