# Generated by Django 3.2.12 on 2023-03-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Sub1', models.IntegerField()),
                ('Sub2', models.IntegerField()),
                ('Sub3', models.IntegerField()),
                ('Sub4', models.IntegerField()),
                ('Sub5', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('avg', models.IntegerField()),
            ],
        ),
    ]
