# Generated by Django 3.2.12 on 2023-03-10 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentresult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='inserted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='avg',
            field=models.CharField(max_length=20),
        ),
    ]
